window.SCALE_STAGES = [
  {
    id: 1,
    slug: "string",
    name: "Fundamental String",
    category: "Theoretical",
    scaleMode: "theoretical",
    characteristicMeters: 1.616255e-35,
    displayScale: "~10⁻³⁵ m",
    qualifier: "Hypothetical · String theory",
    description: "A string-theory scale, not an experimentally observed object.",
    axis: "width",
    asset: "assets/items/01-string.png",
    background: "#FBF9F7"
  },
  {
    id: 2,
    slug: "quark",
    name: "Quark",
    category: "Elementary particles",
    scaleMode: "pointlike-limit",
    characteristicMeters: null,
    experimentalLimitMeters: 1e-20,
    displayScale: "<10⁻²⁰ m probed",
    qualifier: "Point-like within current experiments",
    description: "A fundamental particle with no known internal structure.",
    axis: "width",
    asset: "assets/items/02-quark.png",
    background: "#FAF8FB"
  },
  {
    id: 3,
    slug: "electron",
    name: "Electron",
    category: "Elementary particles",
    scaleMode: "pointlike-symbolic",
    characteristicMeters: null,
    displayScale: "Point-like",
    qualifier: "No measured physical radius",
    description: "An elementary particle with no measured physical radius.",
    axis: "width",
    asset: "assets/items/03-electron.png",
    background: "#F9F8FB"
  },
  {
    id: 4,
    slug: "proton",
    name: "Proton",
    category: "Subatomic",
    scaleMode: "literal",
    characteristicMeters: 1.6815e-15,
    displayScale: "≈1.7 × 10⁻¹⁵ m across",
    qualifier: "",
    description: "A composite particle built from quarks and gluons.",
    axis: "width",
    asset: "assets/items/04-proton.png",
    background: "#FBFAF6"
  },
  {
    id: 5,
    slug: "atomic-nucleus",
    name: "Carbon-12 Nucleus",
    category: "Subatomic",
    scaleMode: "literal",
    characteristicMeters: 5.4e-15,
    displayScale: "≈5.4 × 10⁻¹⁵ m",
    qualifier: "",
    description: "A compact cluster of six protons and six neutrons.",
    axis: "width",
    asset: "assets/items/05-atomic-nucleus.png",
    background: "#FBFAF6"
  },
  {
    id: 6,
    slug: "hydrogen-atom",
    name: "Hydrogen Atom",
    category: "Atomic",
    scaleMode: "literal",
    characteristicMeters: 1.058e-10,
    displayScale: "≈1.1 × 10⁻¹⁰ m",
    qualifier: "Representative atomic scale",
    description: "An electron cloud surrounding a single proton.",
    axis: "width",
    asset: "assets/items/06-hydrogen-atom.png",
    background: "#FBF9F3"
  },
  {
    id: 7,
    slug: "water-molecule",
    name: "Water Molecule",
    category: "Molecular",
    scaleMode: "literal",
    characteristicMeters: 2.75e-10,
    displayScale: "≈0.28 nm",
    qualifier: "",
    description: "One oxygen atom bonded to two hydrogen atoms.",
    axis: "width",
    asset: "assets/items/07-water-molecule.png",
    background: "#FAF9F4"
  },
  {
    id: 8,
    slug: "hemoglobin",
    name: "Hemoglobin",
    category: "Molecular",
    scaleMode: "literal",
    characteristicMeters: 5.5e-9,
    displayScale: "≈5.5 nm",
    qualifier: "",
    description: "A folded protein that carries oxygen in red blood cells.",
    axis: "width",
    asset: "assets/items/08-hemoglobin.png",
    background: "#F9FAF6"
  },
  {
    id: 9,
    slug: "ribosome",
    name: "Ribosome",
    category: "Cellular machinery",
    scaleMode: "literal",
    characteristicMeters: 2.5e-8,
    displayScale: "≈25 nm",
    qualifier: "",
    description: "A molecular machine that builds proteins.",
    axis: "width",
    asset: "assets/items/09-ribosome.png",
    background: "#F7FAF5"
  },
  {
    id: 10,
    slug: "bacteriophage",
    name: "T4 Bacteriophage",
    category: "Microscopic life",
    scaleMode: "literal",
    characteristicMeters: 2.0e-7,
    displayScale: "≈200 nm",
    qualifier: "",
    description: "A virus specialized to infect bacteria.",
    axis: "height",
    asset: "assets/items/10-bacteriophage.png",
    background: "#F5FAF7"
  },
  {
    id: 11,
    slug: "mycoplasma",
    name: "Mycoplasma",
    category: "Microscopic life",
    scaleMode: "literal",
    characteristicMeters: 3.0e-7,
    displayScale: "≈0.3 μm",
    qualifier: "Representative cell dimension",
    description: "Among the smallest independently reproducing cellular organisms.",
    axis: "width",
    asset: "assets/items/11-mycoplasma.png",
    background: "#F4FAF8"
  },
  {
    id: 12,
    slug: "mitochondrion",
    name: "Mitochondrion",
    category: "Cellular machinery",
    scaleMode: "literal",
    characteristicMeters: 1.5e-6,
    displayScale: "≈1.5 μm",
    qualifier: "Representative length",
    description: "A cell organelle that helps produce usable energy.",
    axis: "width",
    asset: "assets/items/12-mitochondrion.png",
    background: "#F4FAF7"
  },
  {
    id: 13,
    slug: "e-coli",
    name: "E. coli",
    category: "Microscopic life",
    scaleMode: "literal",
    characteristicMeters: 2.0e-6,
    displayScale: "≈2 μm",
    qualifier: "Representative cell length",
    description: "A rod-shaped bacterium commonly used in biology research.",
    axis: "width",
    asset: "assets/items/13-e-coli.png",
    background: "#F3FAF8"
  },
  {
    id: 14,
    slug: "yeast",
    name: "Yeast Cell",
    category: "Microscopic life",
    scaleMode: "literal",
    characteristicMeters: 5.0e-6,
    displayScale: "≈5 μm",
    qualifier: "Representative diameter",
    description: "A single-celled fungus.",
    axis: "width",
    asset: "assets/items/14-yeast.png",
    background: "#F4FAF7"
  },
  {
    id: 15,
    slug: "red-blood-cell",
    name: "Red Blood Cell",
    category: "Cellular life",
    scaleMode: "literal",
    characteristicMeters: 7.5e-6,
    displayScale: "≈7.5 μm",
    qualifier: "Typical diameter",
    description: "A flexible human cell specialized for oxygen transport.",
    axis: "width",
    asset: "assets/items/15-red-blood-cell.png",
    background: "#FBF7F4"
  },
  {
    id: 16,
    slug: "sperm-cell",
    name: "Human Sperm Cell",
    category: "Cellular life",
    scaleMode: "literal",
    characteristicMeters: 5.0e-5,
    displayScale: "≈50 μm long",
    qualifier: "",
    description: "A highly specialized human reproductive cell.",
    axis: "width",
    asset: "assets/items/16-sperm-cell.png",
    background: "#F7FAF8"
  },
  {
    id: 17,
    slug: "paramecium",
    name: "Paramecium",
    category: "Microscopic life",
    scaleMode: "literal",
    characteristicMeters: 2.0e-4,
    displayScale: "≈0.2 mm",
    qualifier: "Representative body length",
    description: "A single-celled organism with complex internal structures.",
    axis: "width",
    asset: "assets/items/17-paramecium.png",
    background: "#F3F9F8"
  },
  {
    id: 18,
    slug: "rotifer",
    name: "Rotifer",
    category: "Micro-animals",
    scaleMode: "literal",
    characteristicMeters: 3.0e-4,
    displayScale: "≈0.3 mm",
    qualifier: "Representative body length",
    description: "A microscopic multicellular animal.",
    axis: "height",
    asset: "assets/items/18-rotifer.png",
    background: "#F2F9F8"
  },
  {
    id: 19,
    slug: "tardigrade",
    name: "Tardigrade",
    category: "Micro-animals",
    scaleMode: "literal",
    characteristicMeters: 5.0e-4,
    displayScale: "≈0.5 mm",
    qualifier: "Representative body length",
    description: "A tiny eight-legged animal often called a water bear.",
    axis: "width",
    asset: "assets/items/19-tardigrade.png",
    background: "#F2F8F8"
  },
  {
    id: 20,
    slug: "c-elegans",
    name: "C. elegans",
    category: "Micro-animals",
    scaleMode: "literal",
    characteristicMeters: 1.0e-3,
    displayScale: "≈1 mm",
    qualifier: "Adult body length",
    description: "A tiny roundworm widely used in biological research.",
    axis: "width",
    asset: "assets/items/20-c-elegans.png",
    background: "#F3F8F7"
  },
  {
    id: 21,
    slug: "daphnia",
    name: "Daphnia",
    category: "Micro-animals",
    scaleMode: "literal",
    characteristicMeters: 2.0e-3,
    displayScale: "≈2 mm",
    qualifier: "Representative body length",
    description: "A small freshwater crustacean often called a water flea.",
    axis: "height",
    asset: "assets/items/21-daphnia.png",
    background: "#F4F9F8"
  },
  {
    id: 22,
    slug: "fruit-fly",
    name: "Fruit Fly",
    category: "Visible life",
    scaleMode: "literal",
    characteristicMeters: 2.5e-3,
    displayScale: "≈2.5 mm",
    qualifier: "Representative body length",
    description: "A tiny insect widely used in genetics research.",
    axis: "width",
    asset: "assets/items/22-fruit-fly.png",
    background: "#F8F8F3"
  },
  {
    id: 23,
    slug: "ant",
    name: "Ant",
    category: "Visible life",
    scaleMode: "literal",
    characteristicMeters: 5.0e-3,
    displayScale: "≈5 mm",
    qualifier: "Representative worker length",
    description: "A representative small worker ant.",
    axis: "width",
    asset: "assets/items/23-ant.png",
    background: "#FAF8F3"
  },
  {
    id: 24,
    slug: "ladybird",
    name: "Ladybird Beetle",
    category: "Visible life",
    scaleMode: "literal",
    characteristicMeters: 8.0e-3,
    displayScale: "≈8 mm",
    qualifier: "Representative body length",
    description: "A small rounded beetle.",
    axis: "width",
    asset: "assets/items/24-ladybird.png",
    background: "#FBF8F3"
  },
  {
    id: 25,
    slug: "honey-bee",
    name: "Honey Bee",
    category: "Visible life",
    scaleMode: "literal",
    characteristicMeters: 1.3e-2,
    displayScale: "≈13 mm",
    qualifier: "Representative worker length",
    description: "A representative worker honey bee.",
    axis: "width",
    asset: "assets/items/25-honey-bee.png",
    background: "#FBF8F0"
  },
  {
    id: 26,
    slug: "house-cricket",
    name: "House Cricket",
    category: "Visible life",
    scaleMode: "literal",
    characteristicMeters: 2.0e-2,
    displayScale: "≈20 mm",
    qualifier: "Representative body length",
    description: "A small insect with powerful jumping legs.",
    axis: "width",
    asset: "assets/items/26-house-cricket.png",
    background: "#FAF8F1"
  },
  {
    id: 27,
    slug: "garden-snail",
    name: "Garden Snail",
    category: "Visible life",
    scaleMode: "literal",
    characteristicMeters: 3.5e-2,
    displayScale: "≈35 mm",
    qualifier: "Representative body length",
    description: "A small land mollusc carrying a spiral shell.",
    axis: "width",
    asset: "assets/items/27-garden-snail.png",
    background: "#FAF7F1"
  },
  {
    id: 28,
    slug: "bee-hummingbird",
    name: "Bee Hummingbird",
    category: "Visible life",
    scaleMode: "literal",
    characteristicMeters: 5.82e-2,
    displayScale: "≈5.8 cm",
    qualifier: "Representative total length",
    description: "The world’s smallest living bird species.",
    axis: "width",
    asset: "assets/items/28-bee-hummingbird.png",
    background: "#F8F8F1"
  },
  {
    id: 29,
    slug: "small-mouse",
    name: "Small Mouse",
    category: "Visible life",
    scaleMode: "literal",
    characteristicMeters: 9.0e-2,
    displayScale: "≈9 cm body length",
    qualifier: "Tail excluded",
    description: "A representative small mouse.",
    axis: "width",
    asset: "assets/items/29-small-mouse.png",
    background: "#F8F7F1"
  },
  {
    id: 30,
    slug: "house-sparrow",
    name: "House Sparrow",
    category: "Visible life",
    scaleMode: "literal",
    characteristicMeters: 1.6e-1,
    displayScale: "≈16 cm",
    qualifier: "Representative total length",
    description: "A familiar small bird found around people worldwide.",
    axis: "width",
    asset: "assets/items/30-house-sparrow.png",
    background: "#F9F7F1"
  },
  {
    id: 31,
    slug: "human-hand",
    name: "Human Hand",
    category: "Human scale",
    scaleMode: "literal",
    characteristicMeters: 1.8e-1,
    displayScale: "≈18 cm",
    qualifier: "Representative adult hand length",
    description: "A familiar reference scale from your own body.",
    axis: "height",
    asset: "assets/items/31-human-hand.png",
    background: "#FBF8F3"
  },
  {
    id: 32,
    slug: "rock-cavy",
    name: "Rock Cavy",
    category: "Visible life",
    scaleMode: "literal",
    characteristicMeters: 2.2e-1,
    displayScale: "≈22 cm",
    qualifier: "Body length",
    description: "A small South American mammal related to guinea pigs.",
    axis: "width",
    asset: "assets/items/32-rock-cavy.png",
    background: "#FAF8F2"
  },
  {
    id: 33,
    slug: "red-panda",
    name: "Red Panda",
    category: "Visible life",
    scaleMode: "literal",
    characteristicMeters: 5.9e-1,
    displayScale: "≈59 cm body length",
    qualifier: "Tail excluded",
    description: "A small mammal with a long tail not included in this scale value.",
    axis: "width",
    asset: "assets/items/33-red-panda.png",
    background: "#FAF7F1"
  },
  {
    id: 34,
    slug: "beaver",
    name: "Beaver",
    category: "Visible life",
    scaleMode: "literal",
    characteristicMeters: 1.1,
    displayScale: "≈1.1 m",
    qualifier: "Representative total length",
    description: "A large semi-aquatic rodent.",
    axis: "width",
    asset: "assets/items/34-beaver.png",
    background: "#FAF7F1"
  },
  {
    id: 35,
    slug: "human",
    name: "Human",
    category: "Human scale",
    scaleMode: "literal",
    characteristicMeters: 1.7,
    displayScale: "≈1.7 m",
    qualifier: "Representative standing height",
    description: "You have reached the scale of a person.",
    axis: "height",
    asset: "assets/items/35-human.png",
    background: "#FBFAF6"
  }
];
